import os
from datetime import datetime
from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct
from langchain_openai import OpenAIEmbeddings


def get_qdrant_client():
    """Get Qdrant client instance."""
    return QdrantClient(
        url=os.getenv("QDRANT_URL", "http://localhost:6333"),
        api_key=os.getenv("QDRANT_API_KEY"),
    )


def get_embeddings():
    """Get OpenAI embeddings instance."""
    return OpenAIEmbeddings(
        model="text-embedding-3-large",
        openai_api_key=os.getenv("OPENAI_API_KEY"),
    )


def create_collection_if_not_exists():
    """Create Qdrant collection if it doesn't exist."""
    client = get_qdrant_client()
    collection_name = os.getenv("QDRANT_COLLECTION_NAME", "rag_documents")

    collections = client.get_collections().collections
    if not any(col.name == collection_name for col in collections):
        client.create_collection(
            collection_name=collection_name,
            vectors_config=VectorParams(size=3072, distance=Distance.COSINE),
        )
        print(f"Created collection: {collection_name}")


def add_documents_to_qdrant(documents: list[dict]):
    """
    Add documents to Qdrant with custom structure.

    Expected document structure:
    {
        "text": str,
        "file_name": str,
        "file_ext": str,
        "tags": list[str],
        "chunk_id": int,
        "total_chunks": int,
        "created": str (ISO timestamp)
    }
    """
    client = get_qdrant_client()
    embeddings = get_embeddings()
    collection_name = os.getenv("QDRANT_COLLECTION_NAME", "rag_documents")

    # Generate embeddings for all texts
    texts = [doc["text"] for doc in documents]
    vectors = embeddings.embed_documents(texts)

    # Create points
    points = []
    for i, (doc, vector) in enumerate(zip(documents, vectors)):
        point = PointStruct(
            id=i,  # Will be auto-generated by Qdrant if not provided
            vector=vector,
            payload={
                "text": doc["text"],
                "file_name": doc["file_name"],
                "file_ext": doc["file_ext"],
                "tags": doc["tags"],
                "chunk_id": doc["chunk_id"],
                "total_chunks": doc["total_chunks"],
                "created": doc["created"],
            },
        )
        points.append(point)

    # Upload to Qdrant
    client.upload_points(collection_name=collection_name, points=points)

    return len(points)


def search_documents(query: str, limit: int = 3) -> list[dict]:
    """
    Search for documents in Qdrant.

    Returns list of documents with structure:
    {
        "text": str,
        "file_name": str,
        "file_ext": str,
        "tags": list[str],
        "chunk_id": int,
        "total_chunks": int,
        "created": str,
        "score": float
    }
    """
    client = get_qdrant_client()
    embeddings = get_embeddings()
    collection_name = os.getenv("QDRANT_COLLECTION_NAME", "rag_documents")

    # Generate query embedding
    query_vector = embeddings.embed_query(query)

    # Search
    results = client.search(
        collection_name=collection_name, query_vector=query_vector, limit=limit
    )

    # Format results
    documents = []
    for result in results:
        doc = {
            "text": result.payload["text"],
            "file_name": result.payload["file_name"],
            "file_ext": result.payload["file_ext"],
            "tags": result.payload["tags"],
            "chunk_id": result.payload["chunk_id"],
            "total_chunks": result.payload["total_chunks"],
            "created": result.payload["created"],
            "score": result.score,
        }
        documents.append(doc)

    return documents
